[build]
  publish = "dist"
  command = "astro build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200


[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

