#!/usr/bin/env node
/**
 * Generate site derivatives from the committed originals.
 *
 * `originals/` holds untouched source images (never delete or overwrite them).
 * This script writes WebP derivatives to `public/images/`, capped in width, and
 * prints a media manifest to stdout so provenance stays visible in review.
 *
 *   bun run images
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SOURCES = ["originals/images", "originals/assets", "originals/hero"];
const OUT = path.join(ROOT, "public/images");

const MAX_WIDTH = 1600;
const QUALITY = 80;

function slugify(name) {
  return name
    .normalize("NFKD")
    .toLowerCase()
    .replace(/\.[a-z0-9]+$/i, "")
    .replace(/[()_]+/g, "-")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const manifest = [];
  const used = new Set();

  for (const dir of SOURCES) {
    const abs = path.join(ROOT, dir);
    if (!existsSync(abs)) continue;

    for (const file of (await readdir(abs)).sort()) {
      const src = path.join(abs, file);
      let meta;
      try {
        meta = await sharp(src).metadata();
      } catch {
        console.warn(`skip (unreadable): ${file}`);
        continue;
      }
      if (!meta.width || !meta.height) continue;

      // Distinct source files can reduce to the same basename. Without this,
      // the later write silently overwrites the earlier one and the manifest
      // lies about what exists.
      let name = slugify(file) + ".webp";
      if (used.has(name)) {
        const ext = path.extname(file).replace(/^\./, "").toLowerCase() || "file";
        const base = `${slugify(file)}-${ext}`;
        name = `${base}.webp`;
        let n = 2;
        while (used.has(name)) name = `${base}-${n++}.webp`;
        console.warn(`collision: ${dir}/${file} -> ${name}`);
      }
      used.add(name);
      const dest = path.join(OUT, name);
      const width = Math.min(meta.width, MAX_WIDTH);
      const info = await sharp(src)
        .rotate()
        .resize({ width, withoutEnlargement: true })
        .webp({ quality: QUALITY })
        .toFile(dest);

      manifest.push({
        file: file,
        source: `${dir}/${file}`,
        out: `/images/${name}`,
        original: `${meta.width}x${meta.height}`,
        derivative: `${info.width}x${info.height}`,
        bytes: info.size,
      });
    }
  }

  const rows = manifest
    .map(
      (m) =>
        `| ${m.out.replace("/images/", "")} | ${m.original} | ${m.derivative} | ${(m.bytes / 1024).toFixed(0)} KB | ${m.source} |`,
    )
    .join("\n");

  const doc = `# Media manifest

Generated by \`bun run images\`. Originals live in \`originals/\` and are never
modified. Derivatives are capped at ${MAX_WIDTH}px wide, WebP quality ${QUALITY}.

Many of these files carry descriptive filenames from an earlier migration, not
real captions. Captions, dates, people shown and permission status for each
asset are tracked in \`TODO.md\` and must be confirmed by the association before
they are described publicly.

| File | Original | Derivative | Size | Source |
| --- | --- | --- | --- | --- |
${rows}
`;

  await writeFile(path.join(ROOT, "MEDIA.md"), doc, "utf8");
  console.log(`Wrote ${manifest.length} derivatives and MEDIA.md`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
